/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class D2XX */

#ifndef _Included_D2XX
#define _Included_D2XX
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     D2XX
 * Method:    AccelerometerInit
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_D2XX_AccelerometerInit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     D2XX
 * Method:    AccelerometerRead
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_D2XX_AccelerometerRead
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
